name: repro

on: [ push, pull_request, workflow_dispatch ]

jobs:
  repro:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.4
        with:
          path: ${{ github.job }}-${{ github.run_number }}

      - run: echo hello world
